spring:
  application:
    name: SB-JWT-APP

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/emp
    username: postgres
    password: nic@123
    
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
   
   
security:
      jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600000       