#server:
#  port: 1111

spring:
  application:
    name: MS-WELCOME-API
#Admin server manually we configuring    
  boot:
    admin:
      client:
        url: http://localhost:9090
        
#all actuator endpoints should be exposed
management:
  endpoints:
    web:
      exposure:
        include: '*'
       
        