#spring:
#  application:
#    name: MS-SERVICE-REGISTRY  # FIXED spelling mistake
#
#server:
#  port: 8761  # Eureka server runs on this port
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false  # Server should NOT register itself
#    fetch-registry: false  # Server should NOT fetch other instances
#    


   server:
      port: 8761
   eureka:
        client:
          register-with-eureka: false
     