server:
  port: 2222

spring:
  config:
    import: optional:configserver:http://localhost:6666
  application:
    name: MS-GREET-API

    



#  boot:
#    admin:
#      client:
#        url: http://localhost:8081
#        
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#        
        
                