
server:
  port: 2222
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kumarsb22/ms-config-properties.git
          clone-on-start: true
    

  application:
    name: MS-GREET-API

  boot:
    admin:
      client:
        url: http://localhost:8081
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
        
                