spring:
  application:
    name: SB-AM-MANY-TO-MANY

    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/emp
    username: postgres
    password: nic@123
    
    
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true      
    